service: fastapi-lambda

provider:
  name: aws
  runtime: python3.9
  memorySize: 512
  timeout: 30
  region: us-east-1
  environment:
    S3_BUCKET: "awscostviz"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true # Mac などで問題が起きないようにする
    layer: true # 依存関係を Lambda Layer にする (オプション)

functions:
  api:
    handler: lambda_function.handler
    events:
      - http:
          path: /Forawscostviz
          method: get
